[package]
name = "luminair_utils"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
luminair_air = { path = "../air" }
stwo-prover.workspace = true
